harness/terraform-provider-harness

docs/resources/user_group.md, examples/resources/harness_user_group/resource.tf, go.mod, go.sum, internal/provider/resource_cloudprovider_tanzu.go, internal/provider/resource_git_connector_test.go, internal/provider/resource_infrastructure_definition_test.go, internal/provider/resource_service_aws_codedeploy.go, internal/provider/resource_service_aws_lambda.go, internal/provider/resource_service_winrm.go, internal/provider/resource_user_group.go, internal/provider/resource_user_group_test.go
For the resource "harness_user_group"`, a new section has been added to support granular permissions for templates.
```
template {
template_ids = ["abc123"]
app_ids = ["app123"]
actions = ["CREATE", "READ", "UPDATE", "DELETE"]
}
```
=> Support for usergroup app permission for templates

docs/resources/user.md, go.mod, go.sum, internal/service/cd/user/user.go, internal/service/cd/user/user_test.go
Addresses issue #35 .
You can now specify a list of groups when creating a user.
```
resource "harness_user_group" "test" {
name = "test123"
}
resource "harness_user" "test" {
name      = "test"
email     = "miasdfsdfadsf@test.com"
group_ids = [harness_user_group.test.id]
lifecycle {
ignore_changes = [group_ids]
}
}
```
=> Added support for group_ids with user creation

.changelog/75.txt, docs/data-sources/current_user.md, internal/provider/provider.go, internal/service/ng/data_source_current_user.go
Relating to https://github.com/harness-io/terraform-provider-harness/issues/74 
Removing number first parameter to allow auto generation of code from terraform CDK and pulumi.
=> Modify 2fa_enabled to use a letter first

.changelog/81.txt, CHANGELOG.md, docs/data-sources/environment.md, internal/service/cd/environment/environment_data_source.go, internal/service/cd/environment/environment_data_source_test.go
Adds `environment_id`  to `data "harness_environment"` for looking up an environment. This allows `id` to be set as computed and can be referenced.
Closes #79
=> Fixed issue with environment data source lookup by id

.changelog/115.txt, internal/service/cd/delegate/delegate_approval.go
=> Force new resource when delegate_id or approve fields have changed

internal/service/platform/secret/text_test.go
Secret text was not working because of delay in creating default secret manager after project creation. We have added secret at account level in the test.
=> Fixed secret text test

internal/service/platform/connector/connector.go
Currently terraform fails to delete connectors that are at the org and project level because the identifiers aren't sent in the DELETE request.
This change includes them in the opts so that they're included in the query params.
=> Fix deletion of project and org level connectors

.changelog/430.txt, docs/resources/platform_monitored_service.md, internal/service/platform/monitored_service/resource_monitored_service.go, internal/service/platform/monitored_service/resource_monitored_service_test.go
Terraform Provider - fields template_ref and version_label shouldn't be required for harness_platform_monitored_service
<details>
=> feat: [SRM-13995]: Bug fix in harness_platform_monitored_service

internal/service/platform/secret/secret.go, internal/service/platform/secret/text_test.go
=> Mark new resource when secret deleted from ui

internal/service/platform/connector/aws_kms_test.go, internal/service/platform/connector/aws_secret_manager_test.go, internal/service/platform/connector/azure_key_vault_test.go, internal/service/platform/connector/gcp_secret_manager_test.go, internal/service/platform/connector/pagerduty_test.go, internal/service/platform/connector/vault_test.go, internal/service/platform/resource_group/resource_group_test.go, internal/service/platform/roles/resource_roles_test.go, internal/service/platform/secret/text_test.go, internal/service/platform/service/resource_service_test.go, internal/service/platform/usergroup/usergroup_test.go, internal/service/platform/variables/variables_test.go
1. Added Coverage For Organization & Project Level For Secret Text
2. Added Coverage For Organization & Project Level For Variables
3. Added Coverage For Organization & Project Level For Roles 
4. Added Coverage For Organization & Project Level For Service
5. Added Coverage For Organization & Project Level For Resource Group
6. Added Coverage For Organization & Project Level For AWS KMS
7. Added Coverage For Organization & Project Level For Vault
8. Added Coverage For Organization & Project Level For Pager Duty
9. Added Coverage For Organization & Project Level For GCP SM
10. Added Coverage For Organization & Project Level For Azure Key Vault
11. Added Coverage For Organization & Project Level For AWS SM
12. Added Coverage For Organization & Project Level For User Group
<details> …
=> Coverage Increased For PL Owned Entities

internal/service/platform/variables/data_source_variables_test.go
Added TCs For Data Source Variable
8-8f12-81d8416a2c8b.png">
<details>
=> Added TCs for Data Sources in Variable

.changelog/567.txt, internal/service/platform/usergroup/usergroup.go, internal/service/platform/usergroup/usergroup_test.go
UserGroup CRUD is showing up tfstate is different than the current terraform configuration when applying terraform plan after applying. This is because, the list of users and user_emails is different from the received and the input (in terms of ordering).
This PR handles ignoring of this order
<details>
=> fix: [PL-38768]: Ignore order of userEmails when userGroup is created/updated via terraform

.changelog/553.txt, .changelog/567.txt, docs/resources/platform_connector_github.md, internal/service/platform/connector/github.go, internal/service/platform/connector/github_data_source.go, internal/service/platform/connector/github_test.go
- Adding support for execute on delegate 
<details>
=> CI-8165: fixing github conn

internal/service/platform/usergroup/usergroup_test.go
Removed the UserIds test from userGroup_resource_test.go.
<details>
=> fix: [PL-38768]: Skip the UserGroup test with UserIds

.changelog/570.txt, .changelog/576.txt, docs/resources/platform_monitored_service.md
=> [fix]: [SRM-14907]: adding changes for empty change source changelog and doc

docs/resources/platform_resource_group.md, examples/resources/harness_platform_resource_group/resource.tf, internal/service/platform/resource_group/resource_group.go
We have added more clarity to our documentation for resource group that adds what values we support in **attribute_name** and **attribute_values** field .
Updated the example as well .
This is how it looks now
<details>
=> ER: [PL-39021]: Updated the documentation for Resource Group

.changelog/600.txt, docs/resources/platform_template.md, docs/resources/platform_template_filters.md, internal/service/platform/template/resource_template.go, internal/service/platform/template_filters/resource_template_filters.go
Update the docs for force delete and filter visibility entity
<details>
=> feat: [CDS-71681]: Update the docs

.changelog/618.txt, examples/data-sources/harness_platform_token/data-source.tf, internal/service/platform/api_key/data_source_apiKey.go, internal/service/platform/token/data_source_token.go
Account_id is missing in the data_source docs of apiToken
Also fixed the crashing of the data source for apiKey.
<details>
=> fix: [PL-39958]: Modified apiToken dataSource docs to include accountId

internal/service/platform/service_overrides_v2/resource_service_overrides_v2.go
- The service override list call returns 200 ok for empty responses. In this case, we must mark the resource as a new resource in state file. 
<details>
=> fix: [CDS-76802]: Set as new resource for empty get call

internal/service/platform/environment_service_overrides/resource_environment_service_overrides.go
- The service env override list call returns 200 ok for empty responses. In this case, we must mark the resource as a new resource in state file.
<details>
=> fix: [CDS-76802]: Mark resource as new

.changelog/681.txt, internal/service/platform/file_store/resource_file.go, internal/service/platform/file_store/resource_file_test.go
Previously if file content is changed terraform plan would make no change to tfstate file as file content is computed, this change will make file content field as optional from computed to fetch the file content directly.
<details>
=> fix: [CDS-78671]: Make file content optional

.changelog/687.txt, internal/service/platform/connector/aws.go, internal/service/platform/connector/aws_data_source_test.go
harness_platform_connector_aws -  Set value for cross_account_access if not nil.
<details>
=> fix: [CDS-79070]: Set cross_account_access

docs/resources/platform_feature_flag_target_group.md, internal/service/platform/feature_flag_target_group/resource_feature_flag_target_group.go, internal/service/platform/feature_flag_target_group/resource_feature_flag_target_group_test.go
All other harness tf resource use project_id rather than project, use the same here.
<details>
=> fix: resource_feature_flag_target_group project_id

.changelog/699.txt, docs/resources/platform_feature_flag.md, examples/resources/harness_platform_feature_flag/resource.tf, go.mod, go.sum, internal/service/platform/feature_flag/resource_feature_flag.go, internal/service/platform/feature_flag/resource_feature_flag_test.go
With this change, it is now possible to assign targets and target groups to feature flags on creation. Updates are still limited to the issue in FFM-9600, however, previously we failed to create rules due to an issue in the schema. This change fixes the schema for rules configuration during feature flag creation.
The test cases for this change include:
* Create flag
* add rules to flag
* create flag with rules
* remove rule
<details>
=> FFM-9404: harness_platform_feature_flag cannot add targeting rules

.changelog/700.txt, internal/service/platform/feature_flag/resource_feature_flag.go, internal/service/platform/feature_flag_target/resource_feature_flag_target.go, internal/service/platform/feature_flag_target_group/resource_feature_flag_target_group.go
This change fixes updating and deleting targets and targets groups. It also allows for updating of rules with distributions (i.e 50% for enabled, 50% for disabled), with the weight values being allowed to change. However, there's an issue updating target rules, due to the way we are currently implementing "addRule" and "removeRule" as part of a JavaScript action in the UI that does not translate easily in terraform. 
<details>
=> FFM-9400: TF: harness_platform_feature_flag_target_group does not update

.changelog/731.txt, docs/data-sources/autostopping_schedule.md, docs/resources/autostopping_schedule.md, examples/resources/harness_autostopping_schedule/resource.tf, internal/service/platform/autostopping/schedule/schedule.go, internal/service/platform/autostopping/schedule/schedule_data_source.go, internal/service/platform/autostopping/schedule/schedule_test.go
[Design Doc](https://harness.atlassian.net/wiki/spaces/LWG/pages/21535326993/Terraform+Support+for+Fixed+Schedules)
Type of days attribute in fixed schedule of AutoStopping was string where comma separated values of week day was expected. It has been modified to take list of weekdays for brevity
=> fix: [CCM-14715] Modified days attribute in fixed schedule of AutoStopping

.changelog/743.txt, docs/resources/platform_connector_aws.md, docs/resources/platform_connector_azure_cloud_provider.md, docs/resources/platform_connector_gcp.md, docs/resources/platform_connector_helm.md, docs/resources/platform_connector_kubernetes.md, docs/resources/platform_connector_oci_helm.md, docs/resources/platform_connector_rancher.md, go.mod, go.sum, helpers/schema.go, internal/service/platform/connector/aws.go, internal/service/platform/connector/aws_test.go, internal/service/platform/connector/azure_cloud_provider.go, internal/service/platform/connector/azure_cloud_provider_test.go, internal/service/platform/connector/connector.go, internal/service/platform/connector/gcp.go, internal/service/platform/connector/gcp_test.go, internal/service/platform/connector/http_helm.go, internal/service/platform/connector/http_helm_test.go, internal/service/platform/connector/k8s_cluster.go, internal/service/platform/connector/k8s_cluster_test.go, internal/service/platform/connector/k8s_rancher.go, internal/service/platform/connector/k8s_rancher_test.go, internal/service/platform/connector/oci_helm.go, internal/service/platform/connector/oci_helm_test.go
This changes provide the force_delete option for next connectors:
<details>
=> fix: [CDS-82953]: Add force delete option for aws, azure, gcp, k8s, rancher, oci and helm connectors

docs/resources/platform_resource_group.md, internal/service/platform/resource_group/resource_group.go
When setting up a new resource group using Terraform, if a user neglects to specify the included scopes, the backend (BE) takes charge by automatically populating the default scope. 
However, during subsequent changes, Terraform attempts to make the scope null, assuming it was never defined by the user. The snag arises because the backend doesn't permit this operation; the scope is a required field in our database. To enhance clarity, we're updating our documentation to ensure a more transparent understanding of these intricacies.
<details>
=> [PL-42246] : Added more information in docs to have better clarity

internal/service/platform/secret/file.go
This PR fixes the panic state of the resource Harness Secret File . The details of which are mentioned over here 
Issue -> https://github.com/harness/terraform-provider-harness/issues/773
<details>
=> fix: [PL-43082]: Fixes the Panic State In Harness Secret File Resource

docs/resources/platform_connector_docker.md
Added different documentation links + added more details in doc for the creating the Docker Connector.
<details>
=> fix:CDS-82328:Added Documentation link and more details for the Docker Connector

helpers/yamls.go, helpers/yamls_test.go, internal/service/platform/environment/resource_environment.go, internal/service/platform/environment_group/resource_environment_group.go, internal/service/platform/environment_service_overrides/resource_environment_service_overrides.go, internal/service/platform/infrastructure/resource_Infrastructure.go, internal/service/platform/manual_freeze/resource_manual_freeze.go, internal/service/platform/pipeline/resource_pipeline.go, internal/service/platform/service/resource_service.go, internal/service/platform/service_overrides_v2/resource_service_overrides_v2.go, internal/service/platform/triggers/resource_triggers.go
That allows resource YAML definition using TF functions like that without getting changes in the next `terraform plan` due to YAML string been reformated.
```
yaml       = yamlencode({
variables = [
{
name = "networkEnvironment"
type = "String"
value = each.value.config.env
}
]
})
```
Example of unnecessary change:
```
~ resource "harness_platform_service_overrides_v2" "env_vars" {
id         = "kubernetes_dev"
~ yaml       = <<-EOT
- variables:
-   - name: networkEnvironment
-     type: String
-     value: dev
-     required: false
+ "variables":
+ - "name": "networkEnvironment"
+   "required": false
+   "type": "String"
+   "value": "dev"
EOT
}
```
<details>
- …
=> Add YamlDiffSuppressFunction to avoid unecessary changes in plan

internal/service/platform/connector/aws_secret_manager_test.go, internal/service/platform/connector/gcp_data_source_test.go, internal/service/platform/connector/gcp_secret_manager_data_source_test.go, internal/service/platform/connector/gcp_secret_manager_test.go, internal/service/platform/project/resource_project_test.go, internal/service/platform/secret/text_test.go
This PR skips the test cases which were redundant in regards to the recent change done in the Storing of Secret Managers in Harness SM 
<details>
=> Skipping the TCs which were redundant

internal/service/platform/feature_flag/resource_feature_flag.go
When creating a feature flag via terraform the logic would create the flag then do patch requests if any additional fields were needed that the original post couldn't create. However if no patch instructions were needed at all the patch api request would still send and fail. Then terraform gave the error: `Error: Empty Summary: This is always a bug in the provider and should be reported to the provider developers.`
The fix here is not to send the patch request if no patch instructions are needed. 
<details>
=> fix: [FFM-10392]: Create ff errored without certain optional fields

internal/service/platform/ff_api_key/resource_ff_api_key.go
Previously when getting a conflict when trying to create an api key we'd give a generic terraform error of 
`Error: Empty Summary: This is always a bug in the provider and should be reported to the provider developers.`
Now we give a more descriptive error of 
`Error: An api key with identifier [pricingservice_key] orgIdentifier [default] project [cmproj]  and environment [prod] already exists`
<details>
=> feat: [FFM-10628]: Give descriptive error on api key conflict

internal/service/platform/feature_flag/resource_feature_flag.go
Previously when getting a conflict when trying to create a flag we'd give a generic terraform error of 
`Error: Empty Summary: This is always a bug in the provider and should be reported to the provider developers.`
Now we give a more descriptive error of 
`Error: A flagwith identifier [pricingservice_key] orgIdentifier [default] project [cmproj] already exists`
<details>
=> feat: [FFM-10631]: Custom error for flag conflict

.changelog/859.txt, helpers/schema.go
With this change, resources which have projectId/orgId as required parameters will be deleted in the current scope and new resource will be created in the new scope, whenever the scope parameters (projectId/orgId) are changed in the terraform config.
<details>
=> feat: [PL-46954]: where project and org is required, new resources are created on updating scope.

internal/service/platform/feature_flag/resource_feature_flag.go
Some changes require the flag to be deleted then recreated. To support this we need to force delete the flag, otherwise it will only be archived and then will fail to be created and left in a limbo state
<details>
=> (FFM-10628) Force delete flags for recreate

docs/resources/platform_feature_flag.md, go.sum, internal/service/platform/feature_flag/resource_feature_flag.go, internal/service/platform/feature_flag/resource_feature_flag_test.go
Rewrite of feature flag terraform provider. 
Key changes:
- Use new PUT endpoint for updates - send all flag and environment details in one payload instead of generating a host of patch instructions
- Added ability to set environment activation data - state, default on/off
- Correctly pull down flag data from remote - previously relied on tf state
- Improved logging and error handling - print errors returned from api's instead of generic terraform "something went wrong with the provider" errors
**Limitations**
Target group rules haven't been implemented yet and have been removed from the schema until they're added to the PUT endpoint and work correctly. 
<details>
- …
=> feat:[FFM-10606]: Feature flag v2 terraform provider

.changelog/928.txt, docs/data-sources/platform_connector_kubernetes.md, docs/resources/platform_connector_kubernetes.md, internal/service/platform/connector/k8s_cluster.go, internal/service/platform/connector/k8s_cluster_test.go
Have added support to pass ca certificate for service account based authentication for k8s connector.
Have also removed a duplicate condition on service account based auth type if condition parsing!
<details>
=> fix: [CDS-93065]: add support for CA certificate on k8s connector

docs/resources/platform_feature_flag.md, examples/resources/harness_platform_feature_flag/resource.tf
Name isn't currently supported for ff tags in terraform (it's always assigned the same value as identifier), so remove it from the docs examples or they'll produce errors
<details>
=> (FFM-11100) Update ff tags docs

internal/service/platform/usergroup/usergroup.go
Setting users field to [] explicitly in case user group is SSO-linked
<details>
=> fix: [PL-50642]: Setting users field to [] explicitly in case user group is sso-linked

docs/resources/platform_token.md
Currently, we can't see the Token value created using TF unless the Debug log level is enabled. Adding this to the documentation to clarify for users.
<details>
=> feat: [PL-51935]: Added note to add Debug level logs for seeing Token value created using TF

.changelog/1020.txt, docs/data-sources/platform_gitops_app_project_mapping.md, examples/data-sources/harness_platform_gitops_app_project_mapping/data-source.tf, examples/resources/harness_platform_gitops_app_project_mapping/import.sh, go.mod, go.sum, helpers/schema.go, internal/acctest/acctest.go, internal/service/platform/gitops/app_project/datasource_gitops_app_project_mapping.go, internal/service/platform/gitops/app_project/datasource_gitops_app_project_mapping_test.go, internal/service/platform/gitops/app_project/resource_gitops_app_project_mapping.go, internal/service/platform/gitops/app_project/resource_gitops_app_project_mapping_test.go
changing the import flow
import will be now 
```
terraform import  harness_platform_gitops_app_project_mapping.example org_id/proj_id/<scope_prefixed_agent_id>/argo_proj_name
```
instead of previous 
```
terraform import  harness_platform_gitops_app_project_mapping.example org_id/proj_id/<scope_prefixed_agent_id>/mongo_id
```
related prs
https://github.com/wings-software/gitops/pull/2919
https://github.com/harness/harness-go-sdk/pull/554
<details>
=> fix: [CDS-99254]: Fix import flow for app project mapping

.changelog/1022.txt, go.mod, go.sum, helpers/errors.go, internal/service/platform/gitops/agent/resource_gitops_agent.go, internal/service/platform/gitops/app_project/resource_gitops_app_project_mapping.go, internal/service/platform/gitops/applications/resource_gitops_applications.go, internal/service/platform/gitops/cluster/resource_gitops_cluster.go, internal/service/platform/gitops/gnupg/resource_gnupg.go, internal/service/platform/gitops/project/resource_gitops_app_project.go, internal/service/platform/gitops/repository/data_source_gitops_repository.go, internal/service/platform/gitops/repository/resource_gitops_repository.go, internal/service/platform/gitops/repository_certificates/resource_gitops_repo_certs.go, internal/service/platform/gitops/repository_credentials/resource_gitops_repo_cred.go
When resoruce is deleted outside the terraform flow it should get recreted on terraform apply if resoruce is still in the terraform state file.
Additionally making account, org, project, agent and identifier for repository, cluster and application as immutable fields, as these are not possible to change after creation.
<details>
=> fix: [CDS-100484]: Improve error handling for gitops and recreate gitops resources if they are deleted and existing in terraform state.

docs/resources/platform_token.md, examples/resources/harness_platform_token/resource.tf
At the Org and Project level, we cannot create USER `apikey_type` tokens. Fixed the documentation to reflect the same.
<details>
=> fix: [PL-51691]: Added SERVICE_ACCOUNT as apikey_type for Org and Project level

internal/service/platform/resource_group/resource_group.go
Modified validation for resource group for `attribute_name` field inside `resource_filter`. Testing done:
```
---[ REQUEST ]---------------------------------------
POST /resourcegroup/api/v2/resourcegroup?accountIdentifier=px7xd_BFRCi-pfWPYXVjvw HTTP/1.1
Host: qa.harness.io
User-Agent: terraform-provider-harness-platform-dev
Content-Length: 435
Accept: application/json
Content-Type: application/json
X-Api-Key: ****
Accept-Encoding: gzip
{
"resourceGroup": {
"accountIdentifier": "px7xd_BFRCi-pfWPYXVjvw",
"identifier": "test_NIKE_FN_JG",
"name": "RG Name FN JG",
"tags": {
"foo": "bar"
},
"description": "test",
"allowedScopeLevels": [
"account"
],
"includedScopes": [
{
"filter": "EXCLUDING_CHILD_SCOPES",
"accountIdentifier": "px7xd_BFRCi-pfWPYXVjvw"
}
],
"resourceFilter": {
"resources": [
{ …
```
=> feat: [PL-56822]: Modified validation for Resource Group

.changelog/1023.txt, internal/service/platform/gitops/applications/datasource_gitops_applications.go, internal/service/platform/gitops/applications/resource_gitops_applications.go
If there are multiple argocd projects being mapped to one harness project we must specify argocd project for application otherwise we get ambigous project mapping error.
<details>
=> fix: [CDS-100811]: Add spec.project to fix 'ambigous project mapping' errors

.changelog/1025.txt, internal/service/platform/gitops/project/data_source_gitops_app_project.go, internal/service/platform/gitops/project/data_source_gitops_app_project_test.go, internal/service/platform/gitops/project/resource_gitops_app_project.go
Verified the below scenarios
- teraform apply ( create new one )
- terraform apply ( reruning terraform apply after creating )
- remove project from namespace and rerun it should get create
- terraform apply update ( some of the fields of project itseld )
- terrfaofmr apply rerun ufter update
- try to update some of the fields agent_id, org_id, account_id ( it should be recreated)
- rerun terraform apply after update ( nothing should change )
- remove project from terrafrom resource file and run terraform apply
- rerun terraform apply
<details>
=> fix: [CDS-99032]: Removed the accountIdentifier

internal/service/platform/usergroup/usergroup.go
Setting user_emails only if users is not set in read user group v2. Currently, we support user groups management using 2 variables, either `users` (user IDs) or `user_emails` (user emails). If `users` field is already set, we do not want to set `user_emails`. Due to this, on `terraform plan`, even if there are no changes, it shows a diff because we are setting `user_emails` for a resource where `users` is being used. Testing done:
```
1. Create new resource:
a. Using user_emails
b. Using users (user IDs)
2. Update existing resource
a. Using user_emails
b. Using users (user IDs)
3. Read existing resource
a. Using user_emails
b. Using users (user IDs)
4. Delete existing resource
a. Using user_emails
b. Using users (user IDs)
5. Import existing resource
```
<details>
<summary>PR Check …
=> fix: [PL-57016]: Setting user_emails only if users is not set in read user group v2

internal/service/platform/usergroup/usergroup.go
Reverting usage of GET v2 user group API changes since API is unavailable in SMP environments. This reverts changes in https://github.com/harness/terraform-provider-harness/commit/84985dd76a00a5d037bfdea60d1a4afbed5aef33 and https://github.com/harness/terraform-provider-harness/commit/e7825c1c70dbc325cc5352a19c6fa5f88b0b6acf
<details>
=> fix: [PL-57016]: Reverting v2 user group API changes since API is unavailable in all envs

.changelog/1028.txt, docs/resources/platform_policy.md, internal/service/platform/policy/resource_policy.go, internal/service/platform/policy/resource_policy_test.go
**Title:** [Component/Feature] Import Policies to Terraform fix
**Summary:**
Import Policies to Terraform fix
**Details:**
I updated the helper that was being used for the import function. 
Earlier it was OrgResourceImporter [which potentially means that we can only import org level resources] only now updated to MultiLevelResourceImporter.
https://harness.atlassian.net/browse/PIPE-21769
- Update the resource and execute …
=> Fix: [PIPE-21769]: Import Policies to Terraform fix

docs/resources/platform_file_store_file.md, docs/resources/platform_file_store_folder.md, examples/resources/harness_platform_file_store_file/import.sh, examples/resources/harness_platform_file_store_folder/import.sh
**Title:** Add missing slash separators in file and folder import syntax
**Description:**
This PR addresses an issue where the documentation for file and folder import syntax lacked proper slash separators. Adding these separators ensures clarity and accuracy when referencing file paths during import processes.
**Changes made:**
Updated the file and folder import examples to include the correct slash separators.
Fixed Issue #1016 
**Checklist:**
<details>
=> [Docs]: Add missing slash separators in file and folder import syntax

internal/service/platform/usergroup/usergroup.go
**Title:** Fixed a bug to allow userIds to be imported during terraform import
**Summary:**
This PR fixes a bug in the read context of user group resource.
Current behaviour - "userIds" from the Rest API response are not being read while comparing remote and local state of user groups.
Fixed behaviour - "userIds" will be read from the Rest API response while comparing changes to make via terraform, as well as while importing as resource to terraform state.
Testing-
1. Verified that "terraform import" command imports userIds.
2. Verified that "terraform plan" and "terraform apply" commands compare the userIds in the configuration file with the server-side state of the user-group.
3. CRUD with User IDs
4. CRUD with User emails
5. Creation with User IDs and then changing user emails field …
=> fix: [PL-57535]: Fixed a bug to allow userIds to be imported during terraform import

internal/service/cd_nextgen/connector/cloudProviders/gcp.go
This PR resolves the issue faced my customer as mentioned in the ticket: https://harness.atlassian.net/browse/CDS-104942
**Summary:**
In the case of GCP even when the **execute_on_delegate** was set to False, to setup GCP Connector delegate was mandatorily required which is not the expected case.
**Details:**
To resolve the issue we have replaced **Required** with **Optional** field marked as true due to which delegate selection is mandatory.
Describe how the changes were tested. Include …
=> fix: [CDS-104942]: added support for optional field

internal/service/cd_nextgen/service/data_source_service.go
**Title:**
[data/service] Add user-friendly message when service is not found
**Summary:**
Terraform should show an error message stating that the service could not be found.
**Details:**
[Reference any related issues or tickets ](https://harness.atlassian.net/browse/CDS-105224) …
=> fix: [CDS-105224]: Add user-friendly message when service is not found

helpers/schema.go, helpers/schema_test.go, internal/service/cd_nextgen/service/data_source_service_list.go
**Title:**
Add page and size for service list datasource
**Summary:**
This PR enhances the Terraform provider by adding support for pagination to the service_list datasource. Two new parameters, page and size, have been introduced, allowing users to control the pagination of results when querying services.
**Details:**
N/A
* [CDS-105527](https://harness.atlassian.net/browse/CDS-105527)
- Update the resource and execute …
=> feat: [CDS-105527] Add page and size for service list datasource

.changelog/1032.txt, docs/data-sources/platform_connector_aws.md, internal/service/cd_nextgen/connector/cloudProviders/aws.go, internal/service/cd_nextgen/connector/cloudProviders/aws_data_source.go, internal/service/cd_nextgen/connector/cloudProviders/azure_cloud_provider.go
added execute_on_delagte param support for AWS and AZURE CP Connectors
**Summary:**
we need this support to make sure that our tf providers is working correctly.
**Details:**
- Update the resource and execute terraform apply. …
=> Fix:[IMPENG-324]: added execute_on_delagte param support.

docs/resources/platform_gitops_cluster.md, go.mod, go.sum, internal/service/platform/gitops/cluster/resource_gitops_cluster.go
=> fix: [CDS-105804]: Add forceDelete for GitOps cluster resource

internal/service/cd_nextgen/connector/cloudProviders/aws.go
**Title:**
Enable execute_on_delegate for AWS Connectors Using IRSA Credentials
**Summary:**
When creating a connector that uses IRSA credentials, set the execute_on_delegate attribute to true to ensure proper display on UI.
**Details:**
When the AWS connector use IRSA credentials, the connection will always be made through the delegate, with no other connection method available in this case. The ```harness_platform_connector_aws``` resource must define the ```execute_on_delegate``` attribute when creating the connector so that it is correctly reflected in the user interface (UI).
* https://harness.atlassian.net/browse/CDS-105906
* https://harness.atlassian.net/browse/CDS-105906
Describe how the changes were tested. Include any test cases or …
=> fix: [CDS-106208]: Set the execute_on_delegate attribute to true when creating a connector that use IRSA

internal/service/cd_nextgen/connector/cloudProviders/aws.go
**Title:**
Set execute on delete to true only on create
**Summary:**
This PR addresses an issue with the AWS connector update process. Specifically, when attempting to update an AWS connector using IRSA or inherit from delegate, the `execute_on_delegate` property was incorrectly being set to true.
The fix ensures that the `execute_on_delegate` value is only set during the connector creation process, and not during the update procedure. This resolves unintended behavior during updates and maintains the correct flow for connector management.
**Details:**
- When trying to update an AWS connector, we are pushing it to have the `execute_on_delegate` set to **true**.
- The fix is related to only setting the value during the connector creation, not during the update procedure.
**Related …
=> fix:[CDS-106621]: Set execute on delete to true only on create

.changelog/1160.txt, docs/data-sources/platform_connector_jdbc.md, docs/resources/platform_connector_jdbc.md, examples/resources/harness_platform_connector_jdbc/resource.tf, internal/service/platform/connector/jdbc.go, internal/service/platform/connector/jdbc_data_source.go, internal/service/platform/connector/jdbc_data_source_test.go, internal/service/platform/connector/jdbc_test.go
**Summary:**
This PR handles the new auth type `ServiceAccount` for JDBC connector.
**Details:**
Earlier only UsernamePassword auth type was supported.
https://harness.atlassian.net/browse/DBOPS-845
- Remove the content from resource file and execute terraform apply. …
=> [feat]: [DBOPS-845]: JDBC connector ServiceAccount auth

docs/resources/platform_environment.md, docs/resources/platform_environment_group.md, docs/resources/platform_infrastructure.md, docs/resources/platform_service.md, docs/resources/platform_template.md, internal/service/cd_nextgen/environment/resource_environment.go, internal/service/cd_nextgen/environment/resource_environment_test.go, internal/service/cd_nextgen/environment_group/resource_environment_group.go, internal/service/cd_nextgen/environment_group/resource_environment_group_test.go, internal/service/cd_nextgen/infrastructure/resource_Infrastructure.go, internal/service/cd_nextgen/infrastructure/resource_Infrastructure_test.go, internal/service/cd_nextgen/service/resource_service.go, internal/service/cd_nextgen/service/resource_service_test.go, internal/service/pipeline/template/resource_template.go
**Title**: [Schema] Change `force_delete` Field Type from String to Boolean
**Summary**: Changed the type of `force_delete` field from `String` to `Boolean` across multiple resources to improve type safety and maintain consistency with Terraform best practices. This change affects service, environment, environment group, template, and infrastructure resources.
**Details**:
1. Schema Changes:
- Modified `force_delete` field type from schema.TypeString to schema.TypeBool
- Updated helper function from `BuildFieldForBoolean` to `BuildFieldBool` for proper boolean handling
- Maintained computed and optional attributes
2. Documentation Updates:
- Updated field type documentation from String to Boolean
- Improved description clarity for all affected resources
- Added proper punctuation and …
=> fix: [CDS-107596]: Change `force_delete` to Bool

go.mod, go.sum, internal/service/cd_nextgen/connector/cloudProviders/terraform_cloud.go, internal/service/cd_nextgen/connector/cloudProviders/terraform_cloud_test.go
**Title:** 
- Added missing execute on delegate field to Terraform Cloud Connector.
- Keep the backward compatibility for the existing connector configurations.
**Details:**
The execute_on_delegate field was missing in the Terraform Cloud Connector model, which could impact certain configurations. This update adds the field while ensuring that existing connectors continue to function as expected, maintaining backward compatibility.
**Impact**
- New configurations can now properly set execute_on_delegate.
- No breaking changes for users with existing connector setups.
**Testing**
- Verified that the new field is correctly handled in the model.
- Ensured that legacy configurations remain unaffected.
N/A
Describe how the changes were tested. …
=> fix:[CDS-107597] Added missing execute on delegate field to Terraform Cloud Connector

internal/service/platform/gitops/cluster/resource_gitops_cluster.go
**Title:** Fix constant diff on gitops cluster bearer token field
**Summary:**
Since Gitops Clusters REST API's never return actual secret value of the clusters bearer token, and instead returns a masked value (********), this field constantly reports a diff unless 
```
lifecycle {
ignore_changes = [
request.0.upsert, request.0.cluster.0.config.0.bearer_token,
]
}
```
like in this given example https://registry.terraform.io/providers/harness/harness/latest/docs/resources/platform_gitops_cluster#example-usage is provided, this PR should fix this now by setting the tfstate to the value provided by user and leaves it upto the user to manage their tfstate properly to handle secrets similar to how we are handling for gitops repository currently.
Testing:
[SCENARIO]: Cluster created with old …
=> fix: [CDS-106112]: fix constant diff on gitops cluster bearer token

.changelog/1225.txt, internal/service/platform/gitops/applications/datasource_gitops_applications.go, internal/service/platform/gitops/applications/datasource_gitops_applications_test.go, internal/service/platform/gitops/applications/resource_gitops_applications.go, internal/service/platform/gitops/applications/resource_gitops_applications_test.go
**Title:** Fix GitOps Application Multi-Source Configuration in Terraform Provider
**Summary:**
This PR fixes the handling of multi-source configurations in GitOps applications by properly implementing state management for multiple sources and their associated configurations.
**Details:**
- Added `getSourcesForState` method to properly handle multi-source applications state management
- Fixed value type conversions and null checks for source parameters
- Added schema validation for multi-source specific fields like `ref`
- Added support for Helm-specific fields in multi-source context:
- ignore_missing_value_files
- skip_crds
- skip_tests 
- skip_schema_validation
**Why is the change needed:** 
We were getting the error - "error setting application: Invalid address to set: …
=> fix: [CDS-109153]: Fix GitOps Application Multi-Source Configuration in Terraform Provider

docs/resources/platform_db_schema.md, internal/service/platform/db_schema/resource_db_schema.go
[DBOPS-1073]: Removing instance count and adding conflictwith for schema source and script
**Summary:**
instance_count is added in docs but not needed here as it not a mandatory field. 
adding conflictWith with schema-source and script as we are expecting one at anytime
**Details:**
- Update …
=> [DBOPS-1073]: Removing instance count and adding conflictwith

internal/service/platform/ff_api_key/resource_ff_api_key.go
**Title:** [Component/Feature] 
After creation the api key was not being set in state correctly due to [this pr](https://github.com/harness/terraform-provider-harness/commit/7f432b5f60835f78d576595f3a51293d0299aee0#diff-5e4b1341bc69d6cc722bd1ebb38a046a2b843cafc16e781bb3586356a0cac14eR153)
**Summary:**
Add back reading the response values after the create call
**Details:**
FFM-12475
=> fix: [FFM-12475]: resolve api key not listed issue

docs/resources/platform_template.md, internal/service/pipeline/template/resource_template.go
Title: [Template Resource] Fix identifier field to prevent changes and validate YAML consistency
Summary: This PR fixes an issue with the harness_platform_template resource where changing the identifier field would cause a perpetual diff state. The changes include:
Implemented a CustomizeDiff function that prevents changes to the identifier field after resource creation, making it immutable
Added validation during the plan phase that ensures the identifier in the schema matches the identifier in the template YAML
Updated documentation to clearly indicate that the identifier cannot be changed once the resource is created and must match the YAML template
These changes ensure consistent behavior by preventing identifier changes altogether, which better aligns with the Harness platform's …
=> feat: [PIPE-28924]: Fix identifier field to prevent changes and validate YAML consistency

internal/service/platform/usergroup/usergroup.go
Not setting any values of user/user_emails when isSSOLinked
**Summary:**
Not setting any values of user/user_emails when isSSOLinked
**Details:**
Fix for the issue: https://github.com/harness/terraform-provider-harness/issues/1261#issuecomment-3069231132
Reference: https://github.com/harness/terraform-provider-harness/issues/1261
1. Validated that in case of isSSOLinked, we're not populating users/user_emails fields. Even if the resource file has field as empty, on doing terraform plan, …
=> Not setting any values of user/user_emails when isSSOLinked
