internal/provider/cloudprovider.go, internal/provider/resource_cloudprovider_kubernetes_test.go
=> Force new resource when renaming cloudprovider

internal/service/cd/secrets/encrypted_text.go, internal/service/cd/secrets/encrypted_text_test.go
=> Add support for `secret_reference` when creating secrets

internal/service/cd/yamlconfig/yaml_config.go
=> Fixed yaml delete issue

internal/service/cd/delegate/delegate_ids_data_source.go
I could not make the tests run locally, not sure it need a token or any other credential. 😞 
Let me know if there is any other place that also need to be adjusted
=> Update `ListDelegatesWithFilters` API limit to 100

internal/service/cd/application/application.go
=> Remove debug `fmt.Println` call

.changelog/73.txt, .gitignore, go.mod, go.sum, internal/provider/provider.go, internal/sweep/sweep_test.go
=> Upgraded harness-go-sdk to v0.1.11

.changelog/123.txt, internal/service/cd/cloudprovider/kubernetes.go
Fixes issue #105 where delegate selectors were not properly updating.
=> Fix kubernetes cloudprovider delegate selectors

internal/service/platform/project/resource_project.go, internal/service/platform/project/resource_project_test.go
Fixed the vanishing color in project resource
=> Fixed the vanishing color in project resource

.changelog/204.txt
=> [SPG-217]: adding changelog.

internal/service/platform/environment/resource_environment.go, internal/service/platform/environment/resource_environment_test.go
Add computed true for color field in environment group resource
=> Add computed true for color field in environment group resource

examples/resources/harness_platform_environment_group/resource.tf, internal/service/platform/environment_group/resource_environment_group_test.go
=> [SPG-216]: fixing env group doc

.changelog/216.txt, docs/data-sources/platform_cluster.md, docs/resources/platform_cluster.md, go.mod, go.sum, helpers/tags.go, internal/service/platform/cluster/data_source_cluster.go, internal/service/platform/cluster/resource_cluster.go
- [CDS-43546]: adding linking batch clusters
[CDS-43546]: https://harness.atlassian.net/browse/CDS-43546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CDS-43546]: adding linking batch clusters

docs/data-sources/platform_environment.md, internal/service/platform/environment/data_source_environment.go
=> Fix environment data source

.changelog/233.txt, docs/data-sources/platform_usergroup.md, examples/data-sources/harness_platform_usergroup/data-source.tf, internal/service/platform/usergroup/data_source_usergroup_test.go, internal/service/platform/usergroup/usergroup_test.go
- fixing user group doc and updating the document, Adding more examples
=> [SPG-434]: fixing user group doc and updating the document

docs/data-sources/platform_environment.md, docs/data-sources/platform_service.md, examples/data-sources/harness_platform_environment/data-source.tf, examples/data-sources/harness_platform_service/data-source.tf
=> [SPG-554]: updating doc

docs/resources/platform_infrastructure.md, examples/resources/harness_platform_infrastructure/resource.tf
- getting the following error 
- Had to remove a space 
-
=> [SPG-731]: fixing example for infra

CHANGELOG.md
=> [CDS-44872] updating changelog file

internal/service/platform/pipeline/resource_pipeline.go, internal/service/platform/pipeline/resource_pipeline_test.go
=> Bugfix: Platform Pipeline

docs/data-sources/platform_environment_service_overrides.md, docs/resources/platform_environment_service_overrides.md, examples/data-sources/harness_platform_environment_service_overrides/data-source.tf, examples/resources/harness_platform_environment_service_overrides/resource.tf, helpers/schema.go, internal/service/platform/environment_service_overrides/data_environment_service_overrides.go, internal/service/platform/environment_service_overrides/data_environment_service_overrides_test.go, internal/service/platform/environment_service_overrides/resource_environment_service_overrides.go, internal/service/platform/environment_service_overrides/resource_environment_service_overrides_test.go
* service Override fix for id
<details>
=> [SPG-956]: service Override fix for id

internal/service/platform/pipeline_filters/data_source_pipeline_filters_test.go
- fixing TestAccDataSourcePipelineFiltersOrgLevel test
<details>
=> SPG-1065 fixing TestAccDataSourcePipelineFiltersOrgLevel test

.changelog/318.txt, helpers/errors.go
=> Fix error propagation in new apis

go.mod, go.sum, internal/provider/provider.go
=> SPG-435: Mask API Key in http request logs

docs/resources/platform_role_assignments.md, examples/resources/harness_platform_role_assignments/resource.tf, internal/service/platform/infrastructure/resource_Infrastructure.go, internal/service/platform/infrastructure/resource_Infrastructure_test.go
=> Fix deplyment_type field in infradef resource in ng

.changelog/329.txt, docs/resources/platform_template.md, examples/resources/harness_platform_template/resource.tf, internal/service/platform/template/data_source_template.go, internal/service/platform/template/resource_template.go
=> Fix template resource 

internal/service/platform/environment_service_overrides/data_environment_service_overrides_test.go
=> [SPG-1056] fixing service override test

.changelog/330.txt, internal/service/platform/infrastructure/data_source_Infrastructure.go, internal/service/platform/infrastructure/resource_Infrastructure.go, internal/service/platform/infrastructure/resource_Infrastructure_test.go
=> Fix infrastructure resource when creating multiple infrastructure in same env 

.changelog/334.txt, internal/service/platform/usergroup/data_source_usergroup.go, internal/service/platform/usergroup/data_source_usergroup_test.go
=> Fix user group data source

.changelog/333.txt, helpers/errors.go, internal/service/platform/project/resource_project.go, internal/service/platform/project/resource_project_test.go
=> Fix project refresh

docs/resources/platform_gitops_agent.md, examples/resources/harness_platform_gitops_agent/resource.tf, internal/service/platform/gitops/agent/data_source_gitops_agent_test.go, internal/service/platform/gitops/agent/resource_gitops_agent_test.go, internal/service/platform/gitops/agent_yaml/data_source_gitops_agent_deploy_yaml_test.go
=> changing the example gitops agent type in docs

docs/index.md, templates/index.md.tmpl
=> Fix description on documentation page

.changelog/343.txt, internal/service/platform/connector/connector.go, internal/service/platform/environment/resource_environment.go, internal/service/platform/environment/resource_environment_test.go, internal/service/platform/infrastructure/resource_Infrastructure.go, internal/service/platform/infrastructure/resource_Infrastructure_test.go, internal/service/platform/service/resource_service.go, internal/service/platform/service/resource_service_test.go
=> Handle delete underlying resource scenario

internal/service/cd/environment/environment_test.go, internal/service/cd/environment/infra_custom_test.go
=> Fix environment tests in cg

.changelog/349.txt, internal/service/cd/yamlconfig/yaml_config.go, internal/service/cd/yamlconfig/yaml_config_test.go
=> Fix yaml config resource

.changelog/352.txt, internal/service/platform/connector/github.go, internal/service/platform/connector/github_test.go
=> Fix connector refresh

internal/service/platform/connector/artifactory.go, internal/service/platform/connector/aws.go, internal/service/platform/connector/aws_cc.go, internal/service/platform/connector/aws_kms.go, internal/service/platform/connector/aws_secret_manager.go, internal/service/platform/connector/azure_cloud_cost.go, internal/service/platform/connector/azure_cloud_provider.go, internal/service/platform/connector/azure_key_vault.go, internal/service/platform/connector/bitbucket.go, internal/service/platform/connector/datadog.go, internal/service/platform/connector/docker.go, internal/service/platform/connector/dynatrace.go, internal/service/platform/connector/gcp.go, internal/service/platform/connector/gcp_cloud_cost.go, internal/service/platform/connector/gcp_secret_manager.go, internal/service/platform/connector/git.go, internal/service/platform/connector/gitlab.go, internal/service/platform/connector/http_helm.go, internal/service/platform/connector/jira.go, internal/service/platform/connector/k8s_cluster.go, internal/service/platform/connector/kubernetes_cloud_cost.go, internal/service/platform/connector/newrelic.go, internal/service/platform/connector/nexus.go, internal/service/platform/connector/pagerduty.go, internal/service/platform/connector/prometheus.go, internal/service/platform/connector/splunk.go, internal/service/platform/connector/spot.go, internal/service/platform/connector/sumologic.go, internal/service/platform/connector/vault.go
=> Fix connector resource failure for terraform refresh

internal/service/platform/connector/gcp_test.go, internal/service/platform/connector/git_data_source_test.go, internal/service/platform/connector/git_test.go, internal/service/platform/connector/github_data_source_test.go, internal/service/platform/connector/github_test.go, internal/service/platform/connector/gitlab_data_source_test.go, internal/service/platform/connector/gitlab_test.go, internal/service/platform/connector/http_helm_data_source_test.go, internal/service/platform/connector/http_helm_test.go, internal/service/platform/connector/jira_data_source_test.go, internal/service/platform/connector/jira_test.go, internal/service/platform/connector/k8s_cluster_data_source_test.go, internal/service/platform/connector/k8s_cluster_test.go, internal/service/platform/connector/kubernetes_cloud_cost_data_source_test.go, internal/service/platform/connector/kubernetes_cloud_cost_test.go, internal/service/platform/connector/newrelic_test.go, internal/service/platform/connector/nexus_data_source_test.go, internal/service/platform/connector/nexus_test.go, internal/service/platform/connector/pagerduty_data_source_test.go, internal/service/platform/connector/pagerduty_test.go, internal/service/platform/connector/splunk_data_source_test.go, internal/service/platform/connector/splunk_test.go, internal/service/platform/connector/sumologic_data_source_test.go, internal/service/platform/connector/sumologic_test.go
Remove hardcoded secrets and replace with dynamically created one
<details>
=> Remove hardcoded secrets and replace with dynamically created one

internal/service/platform/connector/appdynamics_data_source_test.go, internal/service/platform/connector/appdynamics_test.go, internal/service/platform/connector/artifactory_data_source_test.go, internal/service/platform/connector/artifactory_test.go, internal/service/platform/connector/aws_kms_data_source_test.go, internal/service/platform/connector/aws_kms_test.go, internal/service/platform/connector/aws_secret_manager_test.go, internal/service/platform/connector/aws_test.go, internal/service/platform/connector/bitbucket_data_source_test.go, internal/service/platform/connector/bitbucket_test.go, internal/service/platform/connector/datadog_data_source_test.go, internal/service/platform/connector/datadog_test.go, internal/service/platform/connector/docker_data_source_test.go, internal/service/platform/connector/docker_test.go, internal/service/platform/connector/dynatrace_data_source_test.go, internal/service/platform/connector/dynatrace_test.go
=> Remove hard coded secrets from connector tests

internal/service/platform/connector/spot_test.go
=> Fix spot connector test

internal/service/platform/connector/github_data_source_test.go, internal/service/platform/connector/spot_data_source_test.go
=> Fix spot connector

internal/service/platform/connector/vault_data_source_test.go, internal/service/platform/connector/vault_test.go
=> Fix vault connector test

.changelog/377.txt, internal/service/platform/connector/connector.go
=> Fix connector delete context

internal/service/platform/connector/bitbucket_test.go
=> Update bitbucket test

internal/service/platform/connector/aws_kms_test.go, internal/service/platform/project/data_source_project_test.go
=> Update tests so that they run in qa account

.changelog/378.txt, docs/resources/platform_environment.md, docs/resources/platform_service.md, examples/resources/harness_platform_environment/resource.tf, examples/resources/harness_platform_service/resource.tf
- update documentation on service and env
<details>
=> [SPG-1521]: update documentation on service and env

internal/service/platform/triggers/data_source_triggers_test.go, internal/service/platform/triggers/resource_triggers_test.go
=> Fix triggers test

internal/service/platform/variables/variables_test.go
=> Fix variable resources acctest

.changelog/387.txt, internal/service/platform/environment_service_overrides/resource_environment_service_overrides.go, internal/service/platform/organization/resource_organization.go, internal/service/platform/organization/resource_organization_test.go, internal/service/platform/role_assignments/role_assignments.go, internal/service/platform/role_assignments/role_assignments_test.go, internal/service/platform/variables/variables.go, internal/service/platform/variables/variables_test.go
=> Change error handling method for resource's read context

internal/service/platform/connector/newrelic_test.go, internal/service/platform/connector/nexus_data_source_test.go, internal/service/platform/connector/nexus_test.go, internal/service/platform/connector/prometheus_data_source_test.go, internal/service/platform/connector/prometheus_test.go, internal/service/platform/connector/splunk_data_source_test.go, internal/service/platform/connector/splunk_test.go, internal/service/platform/connector/sumologic_data_source_test.go, internal/service/platform/connector/sumologic_test.go
=> Update secret in splunk connector

internal/service/platform/connector/appdynamics_test.go
=> Add delay in appdynamics acc test

go.mod, go.sum, internal/service/platform/connector/vault_test.go
=> Update the secret in vault acc test

internal/service/platform/connector/artifactory_data_source_test.go, internal/service/platform/connector/artifactory_test.go, internal/service/platform/connector/aws_kms_data_source_test.go, internal/service/platform/connector/aws_kms_test.go, internal/service/platform/connector/aws_secret_manager_test.go, internal/service/platform/connector/aws_test.go, internal/service/platform/connector/bitbucket_data_source_test.go, internal/service/platform/connector/bitbucket_test.go, internal/service/platform/connector/datadog_data_source_test.go, internal/service/platform/connector/datadog_test.go, internal/service/platform/connector/docker_data_source_test.go, internal/service/platform/connector/docker_test.go, internal/service/platform/connector/dynatrace_data_source_test.go, internal/service/platform/connector/dynatrace_test.go, internal/service/platform/connector/gcp_secret_manager_data_source_test.go, internal/service/platform/connector/gcp_secret_manager_test.go, internal/service/platform/connector/gcp_test.go, internal/service/platform/connector/git_data_source_test.go, internal/service/platform/connector/git_test.go, internal/service/platform/connector/github_data_source_test.go, internal/service/platform/connector/github_test.go, internal/service/platform/connector/gitlab_data_source_test.go, internal/service/platform/connector/gitlab_test.go
=> Add delay between secret and connector resources

internal/service/platform/connector/vault.go
=> Update app role field in vault connector resource

internal/service/platform/user/data_source_user.go, internal/service/platform/user/resource_user.go
=> SPG-443 adding user TF

internal/service/platform/user/data_source_user.go, internal/service/platform/user/resource_user.go, internal/service/platform/user/resource_user_test.go
=> SPG-443 adding user resource.

internal/service/platform/pipeline/data_source_pipeline.go
* fix project import
<details>
=> [SPG-1806] fix project import

.changelog/411.txt, internal/service/platform/usergroup/usergroup.go
=> Fix user group schema

.changelog/413.txt, docs/data-sources/platform_user.md, docs/resources/platform_user.md, internal/service/platform/user/data_source_user.go, internal/service/platform/user/resource_user.go
=> Spg 1837 fix user documentation

internal/service/platform/service/resource_service_test.go
Fixing a test case for service update,we have recently updated that service name and id should be same in yaml and in config.
<details>
=> [CDS-52324]: fixing test case

internal/service/platform/user/data_source_user_test.go, internal/service/platform/user/resource_user_test.go
* we are currently blocked on https://harness.atlassian.net/browse/PL-31383 from the API team meanwhile we want to make the acceptance test stable. hence adding the skip test. 
<details>
=> CDS-52969 adding skip test

.changelog/422.txt, docs/resources/user_group.md, docs/resources/user_group_permissions.md, internal/service/cd/user/user_group_common.go
=> Make filters field option in user group resource for pipeline,workflow,enviroments and services

internal/service/platform/environment_service_overrides/resource_environment_service_overrides.go
- Fix Service Override identifier 
<details>
=> SPG-1932 fix service override id

internal/service/platform/monitored_service/resource_monitored_service.go, internal/service/platform/monitored_service/resource_monitored_service_test.go, internal/service/platform/slo/data_source_slo_test.go, internal/service/platform/slo/resource_slo.go, internal/service/platform/slo/resource_slo_test.go
1. Intermittent test case failures - Added timeout to fix it.
2. Fix SLO test due to recent change wherein name of the service in the YAML should match with the one in request.
3. Add DeleteUnderlyingResource test for SLO & MS resource.
<details>
=> SLO & MS Acc Tests Fixes

.changelog/423.txt, docs/data-sources/platform_environment_service_overrides.md, docs/resources/platform_environment_service_overrides.md, internal/service/platform/environment_service_overrides/data_environment_service_overrides.go, internal/service/platform/environment_service_overrides/data_environment_service_overrides_test.go, internal/service/platform/environment_service_overrides/resource_environment_service_overrides.go, internal/service/platform/environment_service_overrides/resource_environment_service_overrides_test.go
=> Spg 1932 fix service override

internal/service/platform/service/resource_service.go
- Changing service creation/update API call. 
<details>
=> CDS-53213 service creation change

.changelog/437.txt, internal/service/platform/secret/file.go, internal/service/platform/secret/file_test.go
=> Fix secret file resource

internal/service/platform/secret/file_test.go
=> Add delay in secret file acc test

internal/service/platform/gitops/gnupg/data_source_gnupg_test.go, internal/service/platform/gitops/gnupg/resource_gnupg_test.go, internal/service/platform/gitops/repository_certificates/data_source_gitops_repo_cert_test.go, internal/service/platform/gitops/repository_certificates/resource_gitops_repo_certs_test.go
=> fix: GitOps changing repo certs, gnupg keys tests to account level

internal/service/platform/gitops/repository/data_source_gitops_repository_test.go, internal/service/platform/gitops/repository/resource_gitops_repository_test.go, internal/service/platform/gitops/repository_credentials/data_source_gitops_repo_cred_test.go, internal/service/platform/gitops/repository_credentials/resource_gitops_repo_cred_test.go
=> fix: GitOps moving repo creds test to account level

internal/service/platform/environment/resource_environment.go
=> CDS-54094 add create to env

docs/resources/platform_user.md, examples/resources/harness_platform_user/import.sh
PL-31585: Fix Doc Typo
<details>
=> PL-31585: Fix Doc Typo

.changelog/438.txt, docs/data-sources/platform_infrastructure.md, docs/resources/platform_infrastructure.md, examples/resources/harness_platform_infrastructure/import.sh, internal/service/platform/infrastructure/data_source_Infrastructure.go, internal/service/platform/infrastructure/data_source_infrastructure_test.go, internal/service/platform/infrastructure/resource_Infrastructure.go, internal/service/platform/infrastructure/resource_Infrastructure_test.go
-  Updating infra def account/org level
<details>
=> CDS-54161 Updating infra def account/org level

.changelog/451.txt, docs/data-sources/platform_user.md, docs/resources/platform_user.md, examples/resources/harness_platform_user/resource.tf, internal/service/platform/user/resource_user.go
PL-31578 Fix user resource
<details>
=> PL-31578 Fix user resource

docs/resources/platform_user.md, internal/service/platform/user/resource_user.go
PL-31585: Update Documentation for user resource.
<details>
=> PL-31585: Update Documentation

.changelog/454.txt, helpers/errors.go
=> Fix error handler

.changelog/456.txt, CHANGELOG.md
=> Update changelog 

.changelog/457.txt, internal/service/platform/pipeline/resource_pipeline.go, internal/service/platform/pipeline/resource_pipeline_test.go, internal/service/platform/template/resource_template.go, internal/service/platform/template/resource_template_test.go
-  fixing template and pipeline imports
<details>
=> CDS-54653 fixing template and pipeline imports

.changelog/462.txt, internal/service/platform/usergroup/usergroup.go
=> CDS-54653 fix usergroup

docs/resources/platform_infrastructure.md, internal/service/platform/infrastructure/resource_Infrastructure.go, internal/service/platform/usergroup/usergroup.go, internal/service/platform/usergroup/usergroup_test.go
=> Updated The Documentation

.changelog/471.txt, docs/resources/platform_connector_kubernetes_cloud_cost.md, docs/resources/platform_input_set.md, docs/resources/platform_pipeline.md, docs/resources/platform_template.md, go.mod, go.sum, helpers/description_util.go, internal/service/platform/connector/kubernetes_cloud_cost.go, internal/service/platform/input_set/input_set_resource.go, internal/service/platform/pipeline/resource_pipeline.go, internal/service/platform/template/resource_template.go
=> Update connector ref field description

go.mod, go.sum
=> Revert go version

internal/service/platform/connector/vault_data_source_test.go, internal/service/platform/connector/vault_test.go, internal/service/platform/project/data_source_project_test.go, internal/service/platform/usergroup/usergroup_test.go
=> Vault Test Issue

.changelog/478.txt, internal/service/platform/input_set/input_set_resource.go, internal/service/platform/input_set/input_set_resource_test.go, internal/service/platform/triggers/resource_triggers.go, internal/service/platform/triggers/resource_triggers_test.go
=> SPG-2440 fixing import.

.changelog/502.txt, go.mod, go.sum, helpers/errors.go
=> Fix error handler when api key doesnt have enough permissions

docs/data-sources/platform_organization.md
=> Doc Updation for Org got skipped

.changelog/516.txt, internal/service/platform/environment_service_overrides/data_environment_service_overrides.go, internal/service/platform/environment_service_overrides/resource_environment_service_overrides.go
=> [CDS-59061]: Mark service overrides identifier as computed

internal/service/platform/environment_service_overrides/resource_environment_service_overrides_test.go
fixing test to only support qualified scoped environment for service overrides crud
<details>
=> [CDS-58214]: fix test for env ref migration in service overrides

internal/service/platform/infrastructure/resource_Infrastructure_test.go
=> fix: [CDS-68541]: fix for force delete infra test case 

internal/service/platform/api_key/apiKey_test.go, internal/service/platform/api_key/data_source_apiKey_test.go
=> fix: [PL-38509]: Fixed tests of apiKey resource

internal/service/platform/gitops/applications/datasource_gitops_applications_test.go, internal/service/platform/gitops/applications/resource_gitops_applications.go, internal/service/platform/gitops/applications/resource_gitops_applications_test.go
=> fix: [CDS-69732]: fix app test

docs/resources/platform_gitops_applications.md, internal/service/platform/gitops/applications/datasource_gitops_applications.go, internal/service/platform/gitops/applications/resource_gitops_applications.go
=> fix: [CDS-59053]: make identifier optional

docs/resources/platform_template.md, internal/service/platform/template/resource_template.go
=> version required change

internal/service/platform/monitored_service/resource_monitored_service.go, internal/service/platform/monitored_service/resource_monitored_service_test.go
=> [fix]: [SRM-14907]: adding changes for empty change source

.changelog/577.txt, helpers/schema.go, internal/acctest/acctest.go
Import statements not working for infrastructures at org/account level
<details>
=> fix: [CDS-71930]: fix infrastruture import to work at account and org  level

examples/resources/harness_platform_gitops_repository/resource.tf
=> feat: [CDS-70737]: add repository examples

internal/service/platform/template/resource_template.go
- Adding error handling when failure to read template. 
<details>
=> fix: [CDS-72546]: Fix panic on template create flow with incorrect

internal/service/platform/connector/k8s_rancher_data_source_test.go
This test broke due to change in schema for rancher connector.
<details>
=> Fix broken test

internal/service/platform/token/resource_token.go, internal/service/platform/token/resource_token_test.go
fix for showing PAT value in terraform resource
<details>
=> [PL-39802]: fix for showing PAT value in terraform resource

.changelog/604.txt, docs/resources/platform_environment.md, examples/resources/harness_platform_environment/resource.tf
=> [CDS-58214]: fix ng environment sample formatting

docs/data-sources/platform_infrastructure.md, docs/resources/platform_connector_rancher.md, docs/resources/platform_infrastructure.md, examples/resources/harness_platform_connector_rancher/resource.tf
Some static doc corrections
<details>
=> fix: [CDS-56689]: correct docs for rancher connector/infra

helpers/errors.go
This PR adds the error handling for the 403 response code when received , previously it used to return that as a bug which was incorrect now that has been fixed 
<details>
=> fix : [PL-39660] : Added Error Handling for 403 

.changelog/624.txt, CHANGELOG.md, docs/data-sources/platform_token.md, docs/resources/platform_token.md, internal/service/platform/token/data_source_token.go, internal/service/platform/token/resource_token.go
changed tags field as set of strings in Token Resource
<details>
=> fix: [PL-40008]: changed tags field as set of strings in Token Resource

.changelog/625.txt, docs/data-sources/platform_apikey.md, docs/resources/platform_apikey.md, internal/service/platform/api_key/apiKey.go, internal/service/platform/api_key/data_source_apiKey.go
=> fix: [PL-40060]: changed tags field as set of strings in ApiKey resource

.changelog/630.txt, go.mod, go.sum
=> [fix]: [CDS-72208]: Upgrade go-sdk to v0.3.39

internal/service/platform/policy/resource_policy.go, internal/service/platform/policyset/resource_policyset.go, internal/service/platform/policyset/resource_policyset_test.go
=> [fix]:[CDS-75647]: fix policyset showing diff

.changelog/654.txt, .changelog/658.txt, CHANGELOG.md
- Updating change log for releasing two fixes.
<details>
=> fix: [CDS-76802]: Update change log

.changelog/665.txt, internal/service/platform/file_store/file_store_utils.go, internal/service/platform/file_store/resource_file.go, internal/service/platform/file_store/resource_folder.go
Handle null point exception if created by field is nil
<details>
=> fix: [CDS-77684]: Handle null point exception if created by field is nil

internal/service/platform/feature_flag/resource_feature_flag.go, internal/service/platform/feature_flag/resource_feature_flag_test.go
* Add unit test for feature flag terraform plugin
* Fix unit test
<details>
=> FFM-9121: Implement unit tests for feature flag terraform plugin

.changelog/684.txt, docs/resources/platform_feature_flag.md, examples/resources/harness_platform_feature_flag/resource.tf
* Add changelog
* Update documentation
<details>
=> FFM-9321: Perform release for feature flag

internal/service/platform/input_set/input_set_resource.go, internal/service/platform/pipeline/resource_pipeline.go, internal/service/platform/template/resource_template.go
=> Import From Git fixed

.changelog/691.txt, docs/resources/platform_connector_service_now.md, internal/service/platform/connector/service_now.go, internal/service/platform/connector/service_now_data_source.go
=> feat:[CDS-79328]: GAed FF refresh token snow

.changelog/704.txt, docs/data-sources/platform_gitops_agent.md, docs/resources/platform_gitops_agent.md, internal/service/platform/gitops/agent/data_source_gitops_agent.go, internal/service/platform/gitops/agent/data_source_gitops_agent_test.go, internal/service/platform/gitops/agent/resource_gitops_agent.go, internal/service/platform/gitops/agent/resource_gitops_agent_test.go
=> feat: [CDS-76236]: Namespaced install of agent

.changelog/730.txt, docs/data-sources/platform_service_overrides_v2.md, docs/resources/platform_service_overrides_v2.md, internal/service/platform/service_overrides_v2/data_source_service_overrides_v2_test.go, internal/service/platform/service_overrides_v2/resource_service_overrides_v2_test.go
Adding override identifier details in overrides v2 documentation
<details>
=> [feat]: [CDS-82723]: Add override identifier details in overrides v2 documentation

docs/resources/platform_gitops_agent.md, docs/resources/platform_gitops_cluster.md, docs/resources/platform_gitops_gnupg.md, docs/resources/platform_gitops_repo_cert.md, docs/resources/platform_gitops_repo_cred.md, docs/resources/platform_gitops_repository.md, examples/resources/harness_platform_gitops_agent/import.sh, examples/resources/harness_platform_gitops_cluster/import.sh, examples/resources/harness_platform_gitops_gnupg/import.sh, examples/resources/harness_platform_gitops_repo_cert/import.sh, examples/resources/harness_platform_gitops_repo_cred/import.sh, examples/resources/harness_platform_gitops_repository/import.sh
=> techdebt: [CDS-82834]: Improve GitOps Docs

helpers/schema.go, internal/acctest/acctest.go, internal/service/platform/gitops/applications/datasource_gitops_applications_test.go, internal/service/platform/gitops/applications/resource_gitops_applications_test.go, internal/service/platform/gitops/cluster/data_source_gitops_cluster_test.go, internal/service/platform/gitops/cluster/resource_gitops_cluster_test.go, internal/service/platform/gitops/gnupg/data_source_gnupg_test.go, internal/service/platform/gitops/gnupg/resource_gnupg_test.go, internal/service/platform/gitops/repository/resource_gitops_repository.go, internal/service/platform/gitops/repository/resource_gitops_repository_test.go
=> fix: [CDS-83586]: GitOps repository and org level import

.changelog/763.txt, internal/service/platform/ff_api_key/resource_ff_api_key.go
Change error message to use correct interface
<details>
=> FFM-9906: Terraform provider breaking on FF automation

docs/data-sources/platform_delegate_token.md, docs/resources/platform_delegate_token.md
=> Fix:[PL-42907}: Updates the Documentation of Delegate Token Resource in Terraform

README.md
=> Thisrohangupta patch 1

go.mod, go.sum
=> Updated the GO SDK Version

examples/resources/harness_platform_monitored_service/resource.tf, internal/service/platform/monitored_service/data_source_monitored_service_test.go
=> [fix]: [SRM-16226]: Adding health source deseralizr

internal/service/platform/template/data_source_template_test.go, internal/service/platform/template/resource_template_test.go
QA pipeline execution with this branch: https://app.harness.io/ng/account/UKh5Yts7THSMAbccG3HrLA/cd/orgs/default/projects/Pipeline_Terraform/pipelines/terraform_pipeline_test/executions/2lw56E6BTcaIa0H59rl9hw/pipeline?storeType=INLINE
<details>
=> fix: [CDS-84683]: Pipeline template tests stability

helpers/yamls.go, helpers/yamls_test.go, internal/service/platform/environment/resource_environment.go, internal/service/platform/environment_group/resource_environment_group.go, internal/service/platform/environment_service_overrides/resource_environment_service_overrides.go, internal/service/platform/infrastructure/resource_Infrastructure.go, internal/service/platform/manual_freeze/resource_manual_freeze.go, internal/service/platform/pipeline/resource_pipeline.go, internal/service/platform/service/resource_service.go, internal/service/platform/service_overrides_v2/resource_service_overrides_v2.go, internal/service/platform/triggers/resource_triggers.go
* Add YamlDiffSuppressFunction to avoid unecessary changes in plan
* Add YamlDiffSuppressFunction tests
<details>
=> Add YamlDiffSuppressFunction to avoid unecessary changes in plan (#794)

.changelog/814.txt, docs/resources/platform_monitored_service.md
We didn't do _go generate_ last time, just adding example .tf files is not enough we need to do _go generate_ and add the generated .md files explicitly.
<details>
=> fix: [SRM-16346]: updated markdown files from the example files for monitored service.

docs/resources/platform_monitored_service.md, docs/resources/platform_slo.md, examples/resources/harness_platform_monitored_service/resource.tf, examples/resources/harness_platform_slo/resource.tf, internal/service/platform/monitored_service/data_source_monitored_service_test.go, internal/service/platform/monitored_service/resource_monitored_service_test.go, internal/service/platform/slo/resource_slo_test.go
=> feat: [SRM-16346]: updated examples for monitored service and SLO

internal/service/platform/slo/data_source_slo_test.go, internal/service/platform/slo/resource_slo_test.go
=> Update SLO tests.

.changelog/846.txt, .changelog/855.txt, docs/resources/platform_connector_github.md, internal/service/platform/connector/github.go, internal/service/platform/connector/github_test.go
=>  fix: [CI-10883]: added force_delete support for github connector

go.mod, go.sum, helpers/errors.go
=> feat:[PL-43643]: Added error handling for EntityNotFoundException

.changelog/872.txt, helpers/errors.go
Corrected the condition clause for error handling
<details>
=> fix: [PL-43643]: Resolved if condition in error handling 

internal/service/platform/template/resource_template.go
…
feat: [CDS-88642]: update Terrform destroy on templates should have better logging | Unclear error message
<details>
[CDS-88642]: https://harness.atlassian.net/browse/CDS-88642?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [CDS-88642]: update Terrform destroy on templates should have better logging | Unclear error message

internal/service/platform/feature_flag/resource_feature_flag.go
Read environment level attributes from flag read endpoint.
This will populate environment state, default on/off, target rules for each env specified in the terraform resource file.
<details>
=> (FFM-10757) Read environment attributes

internal/service/platform/feature_flag/resource_feature_flag.go
Implement PUT attributes to update environment level attributes, state, default on/off, target rules.
Remove old patch code and segment rule logic for now
<details>
=> (FFM-10756) Implement PUT for environment attributes

internal/service/platform/feature_flag/resource_feature_flag.go
Log ff specific errors if they can be parsed
<details>
=> (FFM-10781)

go.mod
Go version has no breaking change https://tip.golang.org/doc/go1.19
<details>
=> feat: upgrade go version

internal/service/platform/repo_rule_branch/resource_repo_rule_branch_test.go
=> fix: fix ut params for code repo rule

internal/service/platform/api_key/apiKey_test.go, internal/service/platform/api_key/data_source_apiKey_test.go
Reverts harness/terraform-provider-harness#946
=> Revert "fix: Removed Project and Org ApiKey Tests"

internal/service/platform/delegate_token/data_source_delegateToken_test.go
=> fix: Delegate Token Tests

internal/service/platform/infrastructure/resource_Infrastructure_test.go
- Removed Improper UT.
<details>
=> [feat]: [CDS-93926]: Removed Improper UT.

docs/resources/platform_infrastructure.md
- Fixed Import command in Docs.
<details>
=> [feat]: [CDS-94021]: Fixed Import Command For Infrastructures in Docs.

.changelog/957.txt
=> Added changelog

docs/data-sources/platform_service_list.md
=> fix:[CDS-95142]:Corrected the example for the Service List

go.mod, go.sum, internal/service/platform/secret/text.go
This PR, along with https://github.com/harness/harness-go-sdk/pull/523 focuses to support the creation for secrets in a CustomSecretManager. 
<details>
=> feat: [PL-49333]: Support creation for secrets for CustomSecretManager

internal/service/platform/pipeline/resource_pipeline_test.go, internal/service/platform/template/resource_template_test.go
correct project details for import yaml test
<details>
=> fix: [PIPE-18919]: correct project details for import yaml test

internal/service/platform/pipeline/resource_pipeline.go, internal/service/platform/pipeline/resource_pipeline_test.go
1. update pipeline test with tag in yaml and resource file 
2. made change in readPipeline function -> set the tags in it 
<details>
=> [feat]: [PIPE-19057]:updated pipeline test add tags creation and readPipeline method

internal/service/platform/connector/custom_secret_manager.go
=> fix: [PL-51501]: Fix for error 'Invalid format of YAML payload' error when creating CustomSM terraform resource

helpers/errors.go
=> fix:[CDS-96604]: Terraform Update error msg for import of resource

.changelog/978.txt
=> fix: add release note for (#990)

.changelog/1000.txt
Incremented the change.log
<details>
=> feat: [CDS-98026]: Update the release not for TF support for project

.changelog/1006.txt, docs/resources/platform_connector_azure_cloud_cost.md, docs/resources/platform_connector_gcp_cloud_cost.md, internal/service/platform/connector/azure_cloud_cost.go, internal/service/platform/connector/gcp_cloud_cost.go
=> [feat]: [CCM-18618]: Add support for governance in gcp and azure cc connectors

.changelog/1001.txt, .changelog/1002.txt
=> [feat]: [DBOPS-308]: Update release notes for harness_platform_connector_jdbc and harness_platform_db_instance

internal/service/platform/gitops/applications/resource_gitops_applications_test.go
=> feat: [CDS-98219]: Add tests for skipRepoValidation

.changelog/1020.txt, .changelog/1021.txt, internal/service/platform/gitops/app_project/datasource_gitops_app_project_mapping.go
Make identifier computed in data for app project mapping
<details>
=> fix: [CDS-99254]: Make identifier computed in data for app project mapping.

docs/resources/platform_gitops_app_project_mapping.md
=> fix: [CDS-100446]: Fix import doc.

README.md
Update docs with the correct path.
<details>
=> [Docs]: fix provider path

internal/service/platform/api_key/apiKey.go
Import statements were not working for already existing API Key resources in TF. This was happening due to the fact that we were using a generic importer. We have added a custom importer to handle the case for API keys.
Tested the imports for Account, Org and Project scopes for API Keys. Following is the state file, tested with various scopes
```
{
"version": 4,
"terraform_version": "1.5.7",
"serial": 6,
"lineage": "2f485cda-4544-a48f-7b7e-2651e1be9731",
"outputs": {},
"resources": [
{
"mode": "managed",
"type": "harness_platform_apikey",
"name": "test",
"provider": "provider[\"registry.terraform.io/harness/harness\"]",
"instances": [
{
"schema_version": 0,
"attributes": {
"account_id": "px7xd_BFRCi-pfWPYXVjvw",
"apikey_type": "USER",
"default_time_to_expire_token": 2592000000, …
```
=> fix: [PL-56500]: Added custom importer for API Key resource

internal/service/platform/usergroup/usergroup.go
Modified user group resource read to use v2 API. This new API is already released in the latest Harness Go SDK Release.
<details>
=> feat: [PL-55889]: Modified user group resource read to use v2 API

docs/data-sources/platform_workspace.md, docs/resources/platform_workspace.md, examples/resources/harness_platform_workspace/resource.tf, internal/service/platform/workspace/data_source_workspace.go, internal/service/platform/workspace/resource_workspace.go, internal/service/platform/workspace/resource_workspace_test.go
update harness_platform_workspace with SHA functionality by adding repository_sha to request body
<details>
=> feat: [IAC-2472]: update harness_platform_workspace with SHA functionality

docs/data-sources/current_account.md
**Summary:**
Fixed documentation for current account for id field.
https://harness.atlassian.net/browse/PL-57523 
- Add again the resource and execute the terraform apply. (Verify the resource is created)
- Verify the …
=> fix: [PL-57523]: Fixed documentation for current account for id field

docs/resources/platform_role_assignments.md
**Summary:**
Updated documentation for Role assignment resource. Reference: [Link](https://github.com/harness/harness-core/blob/develop/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtils.java#L373)
https://harness.atlassian.net/browse/PL-57533
- Remove the content from …
=> feat: [PL-57533]: Updated documentation for Role assignment resource

go.mod, go.sum, internal/provider/provider.go, internal/service/platform/provider/data_source_provider.go, internal/service/platform/provider/data_source_provider_test.go, internal/service/platform/provider/resource_provider.go, internal/service/platform/provider/resource_provider_test.go
=> feat: [CDS-98117]: Onboard provider APIS to terraform

internal/service/platform/connector/secretManagers/aws_secret_manager_test.go, internal/service/platform/connector/secretManagers/gcp_secret_manager_data_source_test.go, internal/service/platform/connector/secretManagers/gcp_secret_manager_test.go, internal/service/platform/connector/secretManagers/secretManagers.go, internal/service/platform/connector/secretManagers/vault_data_source_test.go, internal/service/platform/connector/secretManagers/vault_test.go, internal/service/platform/user/data_source_user_test.go, internal/service/platform/user/resource_user_test.go, internal/service/platform/usergroup/usergroup_test.go
This is the Test Execution Report after running on `smpairgap` environment.
link - https://app.harness.io/ng/account/UKh5Yts7THSMAbccG3HrLA/all/orgs/default/projects/terraform_platform/pipelines/IETerraformSanity/executions/D7IO6DsBQxGJ7xIJoxkjJA/tests?storeType=INLINE
**Checklist:**
<details>
=> feat: [PL-57903]: fixed the platfrom SM tests logic to skip tests

internal/service/platform/file_store/resource_file.go
**Title:** File store object returns changes even if there are no changes in the script
**Summary:**
File store object returns changes even if there are no changes in the script
**Details:**
The issue occurs when using the "file_content_path property" in the "harness_platform_file_store_file" Terraform resource to create a file store resource. After creating the resource and running terraform plan or terraform apply again without any changes, Terraform incorrectly detects changes in the file content.
- Create the resource and execute terraform …
=> fix: [CDS-100878]: File store object returns changes even if there are no changes in the script

internal/service/cd/account/current_account_data_source_test.go
**Title:** Fixed Endpoint Assertion
**Summary:**
Fixed Endpoint Assertion
- Add again the resource and execute the terraform apply. (Verify the resource is created)
- Verify the import the resource file is working fine.
- In case of remote …
=> fix: [CDS-101927]: Fixed Endpoint Assertion

internal/service/pipeline/gitx/webhook/data_source_gitx_webhook_service_test.go, internal/service/pipeline/gitx/webhook/resource_gitx_webhook_service_test.go
**Title:** Fix Pipeline GitX Webhook Test
**Summary:**
Fix Pipeline GitX Webhook Test
- Add again the resource and execute the terraform apply. (Verify the resource is created)
- Verify the import the resource file is working fine.
- In case …
=> fix: [CDS-101927]: Fix Pipeline GitX Webhook Test

.changelog/1091.txt, docs/data-sources/platform_connector_awscc.md, docs/data-sources/platform_connector_azure_cloud_cost.md, docs/data-sources/platform_connector_gcp_cloud_cost.md, docs/resources/platform_connector_awscc.md, docs/resources/platform_connector_azure_cloud_cost.md, docs/resources/platform_connector_gcp_cloud_cost.md, examples/resources/harness_platform_connector_azure_cloud_cost/resource.tf, examples/resources/harness_platform_connector_gcp_cloud_cost/resource.tf, go.mod, go.sum, internal/service/platform/connector/azure_cloud_cost_data_source.go, internal/service/platform/connector/gcp_cloud_cost.go, internal/service/platform/connector/gcp_cloud_cost_data_source.go
=> feat:[CCM-20085]: Add Governance as feature in all cloud provider CCM connectors

.changelog/1115.txt, internal/service/platform/connector/service_now.go
**Title:** harness_platform_connector_service_now 
**Summary:**
fix unsaved changes in plan for servicenow url without slash
**Details:**
Suppress the difference shown if the service_now_url are equal when both compared after removing / suffix if present. This is needed in the case where .tf file contains url without `/`, then API implementation returns url appended with `/`, which is present in tf state. Then tf plan tries to remove the url. 
**Reference of Code Impl**: https://developer.hashicorp.com/terraform/plugin/sdkv2/schemas/schema-behaviors#diffsuppressfunc
Issue: https://harness.atlassian.net/browse/CDS-101017
Please include the below …
=> fix: [CDS-101017]: fix unsaved changes in plan for snow url without slash

internal/service/platform/connector/secretManagers/gcp_secret_manager_data_source_test.go
=> fix: [PL-58520]: Skipped Google SM test cases as KMS dosen't support reference secrets

go.mod, go.sum
**Title:** Terraform Provider unexpected fails with unauthorized error
**Summary:**
The changes are in go-sdk. We have added a new version of the sdk in the terraform provider.
**Details:**
- Remove …
=> fix: [DBOPS-743]: Terraform Provider unexpected fails with unauthorized error

docs/data-sources/platform_db_schema.md, docs/resources/platform_db_schema.md, go.mod, go.sum, internal/service/platform/db_instance/data_source_db_instance_test.go, internal/service/platform/db_instance/resource_db_instance_test.go, internal/service/platform/db_schema/data_source_db_schema.go, internal/service/platform/db_schema/data_source_db_schema_test.go, internal/service/platform/db_schema/resource_db_schema.go, internal/service/platform/db_schema/resource_db_schema_test.go
=> fix : [DBOPS-743]: DBOps Added archivePath support

.changelog/1133.txt
=> fix: [PIPE-24072]: Update the Doc for Pipeline execution filter

internal/service/cd_nextgen/connector/cloudProviders/aws_data_source_test.go
=> fix aws datasource

.changelog/1162.txt, internal/service/platform/gitops/project/resource_gitops_app_project.go
=> fix: [CDS-102254]: fix appproject schema

internal/service/platform/connector/secretManagers/aws_secret_manager_test.go, internal/service/platform/connector/secretManagers/gcp_kms_data_source_test.go, internal/service/platform/connector/secretManagers/gcp_kms_test.go
Fix: [PL-60497]: update the aws recovery tests
**Summary:**
**Details:**
- Remove the content from resource file and execute …
=> fix: [PL-60497]: update the aws recovery tests

internal/service/platform/feature_flag/resource_feature_flag.go
**Title:** [Component/Feature] Add support for archiving/restoring flags
**Summary:**
Adds support for archiving/restoring flags and fixes an issue where flags deleted manually via the UI wouldn't have their state automatically fixed when terraform apply was run.
Note there is a limitation in that the restore flag api only works when a valid environment is passed, for this reason we can only allow flags to be restored via terraform if they have an environment configured. This would need to be addressed as a separate issue on the feature flag service itself before removing this check. 
FFM-12248
Scenarios tested
- Archive/restore flags via tf
- Manually archive/delete flags via UI and confirm state is corrected when running terraform apply …
=> fix: [FFM-12248]: archiving/restore support

internal/service/har/registry/resource_registry.go, internal/service/har/registry/resrouce_registry_test.go
**Title:** Added Support for Upstream Registry
**Summary:**
Added Support for Upstream Registry
**Details:**
Added Support for Upstream Registry
- Add again the resource and execute …
=> feat: [AH-915]: Added Support for Upstream Registry

go.mod, go.sum, internal/service/cd_nextgen/environment/resource_environment.go, internal/service/cd_nextgen/infrastructure/resource_Infrastructure.go, internal/service/cd_nextgen/service/resource_service.go, internal/service/cd_nextgen/service_overrides_v2/resource_service_overrides_v2.go, internal/service/pipeline/input_set/input_set_resource.go, internal/service/pipeline/pipeline/resource_pipeline.go, internal/service/pipeline/pipeline/resource_pipeline_test.go
=> feat: [CDS-107148]: Changes to support edit git details api

.goreleaser.yml
**Title:** Revert back .goreleaser.yml
**Summary:**
Revert back .goreleaser.yml
**Details:**
Revert back .goreleaser.yml
- Add again the resource and execute the terraform apply. …
=> Revert back .goreleaser.yml

.github/CODEOWNERS
**Title:** Add to CodeOwner
**Summary:**
Add to CodeOwner to directories and all their subdirectories:
- internal/service/cd/**
- internal/service/cd_nextgen/**
- internal/service/har/**
- internal/service/pipeline/**
- Add again the resource …
=> Add to CodeOwner

.changelog/1187.txt
=> feat: [IAC-3369]: changelog

internal/service/cd_nextgen/environment/resource_environment.go, internal/service/cd_nextgen/infrastructure/resource_Infrastructure.go, internal/service/cd_nextgen/service/resource_service.go, internal/service/cd_nextgen/service_overrides_v2/resource_service_overrides_v2.go, internal/service/pipeline/input_set/input_set_resource.go, internal/service/pipeline/pipeline/resource_pipeline.go
=> feat: [CDS-107148]: Update branch_name to branch in git details

examples/resources/harness_platform_repo/resource.tf
=> fix: change doc for harness code to not have name

internal/service/platform/gitops/applicationset/resource_gitops_applicationset_test.go
=> fix: [CDS-111598]: fix appset test for all cluster generator

internal/service/platform/db_schema/data_source_db_schema.go
=> fix doc gen

docs/data-sources/platform_workspace.md, docs/resources/platform_workspace.md, examples/resources/harness_platform_workspace/resource.tf
=> IAC-4116: docs

helpers/errors.go, internal/service/platform/policyset/resource_policyset.go
**Title:** improve policy API error handling
**Summary:**
improve policy API error handling
https://harness.atlassian.net/browse/PIPE-24522
- Add again the resource and execute the terraform apply. (Verify the resource is …
=> feat: improve policy API error handling

docs/resources/platform_delegatetoken.md, internal/service/platform/delegate_token/resource_delegateToken.go
Updated Description to write REVOKING method i.e To revoke a token, set token_status field to "REVOKED".
**Summary:**
Updated Description to write REVOKING method i.e To revoke a token, set token_status field to "REVOKED".
**Details:**
Updated Description to write REVOKING method i.e To revoke a token, set token_status field to "REVOKED".
- None, changed description
**Screenshots:**
Include before and after screenshots to visually demonstrate the changes.
**Checklist:**
<details>
=> Updated Description to write REVOKING method
